site_name: nanocosmos Docs
pages:
- Home: index.md
- About: about.md
- nanostream:
  - Web api: nanostream/web/nanostream-4.x-web-api.md
  - iOS api: nanostream/ios/nanostream-ios-sdk.md
  - MacOS api: nanostream/macos/nanostream-macos-sdk.md
  - Android nanoStream SDK:
    - 'Getting Started': 'nanostream/android/getting-started.md'
    - 'Advanced Settings/Usage': 'nanostream/android/android-advanced-settings.md'
    - 'RTMP Playback': 'nanostream/android/rtmp-playback.md'
- bintu.live :
  - Android SDK: 'bintu/android/bintu-android-sdk.md'
  - Getting: 'bintu/index.md'

#theme: readthedocs
theme: yeti

markdown_extensions:
  - markdown_include.include
  - smarty
  - toc:
      permalink: True
      separator: "_"
#extra_css: [extra.css]
