site_name: nanocosmos Docs
pages:
- Home: index.md
- About: about.md
- nanostream:
  - Language Integration :
      - C++ : 'nanostream/general/nanostream_cpp_integration.md'
      - C# : 'nanostream/general/nanostream_csharp_integration.md'
      - Delphi : 'nanostream/general/nanostream_delphi_integration.md'
  - Web api: nanostream/web/nanostream-4.x-web-api.md
  - iOS api: nanostream/ios/nanostream-ios-sdk.md
  - MacOS api: nanostream/macos/nanostream-macos-sdk.md
  - Android api:
    - Streaming Developer Manual : 'nanostream/android/android_developer_manual_streaming.md'
    - Playback Developer Manual : 'nanostream/android/android_developer_manual_playback.md'
    - Sample Developer Manual : 'nanostream/android/android_developer_manual_sample.md'
  - Windows api:
    - Components: 'nanostream/windows/windows_components.md'
    - Binary Modules: 'nanostream/windows/windows_binares.md'
  - Additional Knowledge:
      - RTMP: 'nanostream/support/nanostream_rtmp_all.md'
- bintu.live :
  - Android SDK: 'bintu/android/bintu-android-sdk.md'
  - iOS:
    - SDK Documentation: 'bintu/ios/bintu_ios_sdk.md'
    - Sample Documentation: 'bintu/ios/bintu_ios_sample.md' 
  - Getting: 'bintu/index.md'

#theme: readthedocs
theme: united

markdown_extensions:
  - markdown_include.include
  - smarty
  - toc:
      permalink: True
      separator: "_"
#extra_css: [extra.css]
