site_name: nanocosmos Docs
pages:
- Home: index.md
- About: about.md
- nanostream:
  - Web:
    -API Manual: nanostream/web/nanostream-4.x-web-api.md
    -Javascript Integration: nanostream/web/nanostream_javascript_integration.md
  - iOS api: nanostream/ios/nanostream-ios-sdk.md
  - MacOS api: nanostream/macos/nanostream-macos-sdk.md
  - Android:
    - Streaming Developer Manual : 'nanostream/android/android_developer_manual_streaming.md'
    - Playback Developer Manual : 'nanostream/android/android_developer_manual_playback.md'
    - Sample Developer Manual : 'nanostream/android/android_developer_manual_sample.md'
  - Windows api:
    - Developer Manual: 'nanostream/windows/windows_developer_manual.md'
    - Binary Modules: 'nanostream/windows/windows_binares.md'
    - License Help: 'nanostream/windows/windows_license_help.md'
    - RTMP Network Render & Writer: 'nanostream/windows/windows_networkwriter.md'
    - Language Integration :
        - C++ : 'nanostream/windows/language_integration/nanostream_cpp_integration.md'
        - C# : 'nanostream/windows/language_integration/nanostream_csharp_integration.md'
        - Delphi : 'nanostream/windows/language_integration/nanostream_delphi_integration.md'
        - VisualC : 'nanostream/windows/language_integration/nanostream_activex_visualcpp.md'
        - MFC : 'nanostream/windows/language_integration/nanostream_activex_visualcpp_mfc.md'
  - Additional Knowledge:
      - RTMP: 'nanostream/support/nanostream_rtmp_all.md'
- bintu.live :
  - Android SDK: 'bintu/android/bintu-android-sdk.md'
  - iOS:
    - SDK Documentation: 'bintu/ios/bintu_ios_sdk.md'
    - Sample Documentation: 'bintu/ios/bintu_ios_sample.md'
  - Getting: 'bintu/index.md'

#theme: readthedocs
theme: united

markdown_extensions:
  - markdown_include.include
  - smarty
  - toc:
      permalink: True
      separator: "_"
#extra_css: [extra.css]
